name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependencies: [lowest, highest]
        php-versions:
          - 8.1
          - 8.2
    if: github.event.pull_request.draft == false
    name: PHP ${{ matrix.php-versions }} checks with ${{ matrix.dependencies }} dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json **/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - name: Install lowest dependencies
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --prefer-lowest --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Install highest dependencies
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Run checks lowest
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer test

      - name: Run checks highest
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer check
